import { QuarterScenario } from "./GameSession";

export const SCENARIOS: readonly QuarterScenario[] = [
  {
    quarter: 1,
    season: "Spring",
    event: {
      title: "Opening quarter",
      summary: "The shop opens with modest awareness and room to establish its position.",
    },
    defaultDecision: {
      price: 520,
      marketing: 200_000,
      staff: 3,
      bigMove: "none",
    },
    outcome: {
      headline: "A steady opening established the operating baseline",
      revenue: 1_420_000,
      costOfGoodsSold: 210_000,
      operatingExpenses: 950_000,
      profit: 260_000,
      demand: 3_020,
      capacity: 3_360,
      lostSales: 0,
      stateAfter: {
        cash: 3_260_000,
        debt: 370_000,
        loyalty: 668,
        morale: 70,
        marketShare: 32,
      },
      eventEffect: "No external event. The quarter established the operating baseline.",
    },
  },
  {
    quarter: 2,
    season: "Early summer",
    event: {
      title: "Shimokitazawa local festival",
      summary: "Foot traffic rises sharply while nearby shops compete for attention.",
    },
    defaultDecision: {
      price: 540,
      marketing: 500_000,
      staff: 4,
      bigMove: "none",
    },
    outcome: {
      headline: "Festival demand exposed the shop's first capacity constraint",
      revenue: 2_210_000,
      costOfGoodsSold: 350_000,
      operatingExpenses: 1_300_000,
      profit: 560_000,
      demand: 4_420,
      capacity: 4_100,
      lostSales: 320,
      stateAfter: {
        cash: 3_820_000,
        debt: 340_000,
        loyalty: 720,
        morale: 65,
        marketShare: 34,
      },
      eventEffect: "Festival traffic increased demand and exposed a capacity limit.",
      turningPoint: true,
    },
  },
  {
    quarter: 3,
    season: "Summer",
    event: {
      title: "Frost in Brazil",
      summary: "Wholesale bean prices jump as importers warn of elevated costs.",
    },
    defaultDecision: {
      price: 560,
      marketing: 450_000,
      staff: 4,
      bigMove: "loyalty-program",
    },
    outcome: {
      headline: "A profitable quarter, with pressure behind the numbers",
      revenue: 2_000_000,
      costOfGoodsSold: 200_000,
      operatingExpenses: 1_180_000,
      profit: 620_000,
      demand: 3_760,
      capacity: 4_100,
      lostSales: 0,
      stateAfter: {
        cash: 4_440_000,
        debt: 310_000,
        loyalty: 760,
        morale: 61,
        marketShare: 36,
      },
      eventEffect: "Premium beans supported quality while a higher price moderated demand.",
    },
  },
  {
    quarter: 4,
    season: "Rainy season",
    event: {
      title: "A week of heavy rain",
      summary: "Walk-in traffic falls despite continued neighborhood awareness.",
    },
    defaultDecision: {
      price: 550,
      marketing: 700_000,
      staff: 4,
      bigMove: "none",
    },
    outcome: {
      headline: "The business remained profitable through weaker traffic",
      revenue: 1_780_000,
      costOfGoodsSold: 240_000,
      operatingExpenses: 1_220_000,
      profit: 320_000,
      demand: 3_240,
      capacity: 4_100,
      lostSales: 0,
      stateAfter: {
        cash: 4_760_000,
        debt: 280_000,
        loyalty: 790,
        morale: 58,
        marketShare: 37,
      },
      eventEffect: "Heavy rain reduced walk-in demand despite additional marketing.",
    },
  },
  {
    quarter: 5,
    season: "Late summer",
    event: {
      title: "Premium bean shortage",
      summary: "Supplier prices rise and premium inventory becomes harder to secure.",
    },
    defaultDecision: {
      price: 590,
      marketing: 350_000,
      staff: 4,
      bigMove: "none",
    },
    outcome: {
      headline: "Higher input costs compressed an otherwise stable quarter",
      revenue: 1_980_000,
      costOfGoodsSold: 420_000,
      operatingExpenses: 1_350_000,
      profit: 210_000,
      demand: 3_410,
      capacity: 4_100,
      lostSales: 0,
      stateAfter: {
        cash: 4_970_000,
        debt: 260_000,
        loyalty: 810,
        morale: 55,
        marketShare: 38,
      },
      eventEffect: "The shortage increased premium bean cost and compressed margin.",
      turningPoint: true,
    },
  },
  {
    quarter: 6,
    season: "Autumn",
    event: {
      title: "Repeat customers return",
      summary: "Established customers create stronger and more predictable demand.",
    },
    defaultDecision: {
      price: 610,
      marketing: 600_000,
      staff: 5,
      bigMove: "loyalty-program",
    },
    outcome: {
      headline: "Loyal demand grew without exhausting the expanded capacity",
      revenue: 2_250_000,
      costOfGoodsSold: 340_000,
      operatingExpenses: 1_450_000,
      profit: 460_000,
      demand: 3_890,
      capacity: 5_100,
      lostSales: 0,
      stateAfter: {
        cash: 5_430_000,
        debt: 240_000,
        loyalty: 850,
        morale: 54,
        marketShare: 40,
      },
      eventEffect: "The loyalty program improved repeat demand without exhausting capacity.",
    },
  },
  {
    quarter: 7,
    season: "Early winter",
    event: {
      title: "Espresso machine repair",
      summary: "Equipment downtime reduces practical capacity and adds repair expense.",
    },
    defaultDecision: {
      price: 620,
      marketing: 300_000,
      staff: 5,
      bigMove: "renovate",
    },
    outcome: {
      headline: "Repairs constrained the quarter, but the ledger remained positive",
      revenue: 1_960_000,
      costOfGoodsSold: 310_000,
      operatingExpenses: 1_430_000,
      profit: 220_000,
      demand: 3_620,
      capacity: 4_080,
      lostSales: 0,
      stateAfter: {
        cash: 5_650_000,
        debt: 220_000,
        loyalty: 880,
        morale: 50,
        marketShare: 41,
      },
      eventEffect: "Repair costs and reduced equipment capacity constrained the quarter.",
    },
  },
  {
    quarter: 8,
    season: "Year-end",
    event: {
      title: "Year-end gathering season",
      summary: "Holiday gatherings reward shops with established loyalty and quality.",
    },
    defaultDecision: {
      price: 640,
      marketing: 800_000,
      staff: 5,
      bigMove: "none",
    },
    outcome: {
      headline: "The final quarter closed a profitable eight-quarter run",
      revenue: 2_220_000,
      costOfGoodsSold: 330_000,
      operatingExpenses: 1_300_000,
      profit: 590_000,
      demand: 4_640,
      capacity: 5_100,
      lostSales: 0,
      stateAfter: {
        cash: 6_240_000,
        debt: 198_000,
        loyalty: 923,
        morale: 48,
        marketShare: 42,
      },
      eventEffect: "Year-end demand rewarded the established reputation and quality position.",
      turningPoint: true,
    },
  },
];
